language: node_js

node_js:
  - "4"
  - "6"
  - "7"
  - "8"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - .eslintcache

before_install:
  - yarn --version

script:
  - yarn run lint
  - yarn run test
  - yarn run test-build
