language: node_js

node_js:
  - "4"
  - "6"
  - "7"

sudo: required

cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules
    - packages/vitruvius/node_modules
    - packages/vitruvius-build-package/node_modules
    - .eslintcache

before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn --version

install: yarn

script:
  - yarn run lint
  - yarn run test
