language: node_js

node_js:
  - "4"
  - "6"
  - "7"

sudo: required

cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules
    - packages/vitruvius/node_modules
    - packages/vitruvius-build-package/node_modules
    - .eslintcache

install: yarn

script:
  - yarn run lint
  - yarn run test
