notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"

cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - curl -fsSL -o yarn.js https://github.com/yarnpkg/yarn/releases/download/v0.27.5/yarn-0.27.5.js
  - node ./yarn.js --version
  - node ./yarn.js install

build: off

test_script:
  - node ./yarn.js run test -- --updateSnapshot --color
  - node ./yarn.js run test-build -- --color
